# golangci-lint configuration for jira-ai-issue-solver

# Configuration version
version: "2"

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

# output configuration options
output:
  formats:
    # Text format with colors, line numbers, and linter names
    text:
      print-issued-lines: true
      print-linter-name: true
      colors: true

issues:
  # make issues output unique by line, default is true
  uniq-by-line: true

  # List of regexps of issue texts to exclude.
  exclude:
    - 'declaration of "err" shadows declaration at'

  exclusions:
    # Which file paths to exclude: they will be analyzed, but issues from them won't be reported.
    paths:
      - "bin/.*"
      - "mocks/.*"

formatters:
  enable:
    - gci            # Import order and grouping
    - gofmt          # Checks whether code was gofmt-ed
    - goimports      # Checks import statements are formatted according to the 'goimport' command

  settings:
    gci:
      sections:
        - standard                               # Standard library packages
        - default                                # All other packages
        - prefix(jira-ai-issue-solver)          # Local packages

linters:
  disable:
    - asciicheck     # Disabled due to dependency issues
  enable:
    - copyloopvar    # Detects places where loop variables are copied incorrectly
    - errcheck       # Checks for unchecked errors
    - gocyclo        # Computes and checks the cyclomatic complexity of functions
    - gosec          # Inspects source code for security problems
    - govet          # Reports suspicious constructs
    - ineffassign    # Detects when assignments to existing variables are not used
    - misspell       # Finds commonly misspelled English words in comments
    - nolintlint     # Reports ill-formed or insufficient nolint directives
    - staticcheck    # Go static analysis, detecting bugs, performance issues, and more
    - unconvert      # Removes unnecessary type conversions
    - unused         # Checks for unused constants, variables, functions and types

  settings:
    govet:
      enable:
        - shadow       # Report shadowed variables
      settings:
        printf:
          funcs:
            - (go.uber.org/zap.SugaredLogger).Infof
            - (go.uber.org/zap.SugaredLogger).Warnf
            - (go.uber.org/zap.SugaredLogger).Errorf
            - (go.uber.org/zap.SugaredLogger).Fatalf

    gocyclo:
      # Minimal code complexity to report
      min-complexity: 35

    gosec:
      # Exclude specific checks
      excludes:
        - G204 # Subprocess launched with variable - acceptable for CLI wrappers
        - G306 # File permissions - acceptable for test files
